name: Ethics Guard Compliance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ethics-guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          # Token for the repository (GitHub sets this automatically)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Provide custom messages for issues and PRs
          # issue-message: "Welcome and thank you for your first issue!"
          # pr-message: "Thank you for your first PR!"

      - name: Verify lock integrity matches working files
        run: |
          set -euo pipefail
          WANT_SCRIPT=$(awk -F= '/^script_sha256=/{print $2}' .bit/ethics-guard.lock)
          WANT_SPEC=$(awk -F= '/^spec_sha256=/{print $2}' .bit/ethics-guard.lock)
          GOT_SCRIPT=$(sha256sum tools/ethics-guard.sh | awk '{print $1}')
          GOT_SPEC=$(sha256sum .bit/environment.ethics.yml | awk '{print $1}')
          echo "script want=$WANT_SCRIPT got=$GOT_SCRIPT"
          echo "spec   want=$WANT_SPEC  got=$GOT_SPEC"
          [[ "$WANT_SCRIPT" == "$GOT_SCRIPT" ]] || { echo "Script hash mismatch"; exit 2; }
          [[ "$WANT_SPEC" == "$GOT_SPEC" ]] || { echo "Spec hash mismatch"; exit 2; }

      - name: Run Ethics Guard (ALN Strict)
        env:
          BIT_HUB_NODE_ID: ${{ runner.name }}
          ALN_COMPLIANCE_MODE: "1"
          ALN_FAILSAFE: "0"
          # Optional: Export BIT_HUB_SIGNING_KEY in secrets/mount for signing artifacts
          # BIT_HUB_SIGNING_KEY: /secure/keys/bithub-ci.pem
        run: |
          ./tools/ethics-guard.sh .bit/environment.ethics.yml strict compliance_report.json compliance_report.aln

      - name: Upload compliance artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ethics-compliance-${{ github.run_id }}
          path: |
            compliance_report.json
            compliance_report.json.sha3
            compliance_report.aln
            artifacts/
