name: BitBot Meta Workflow Corrector v2 (Non-Failing)

on:
  push:
    paths:
      - ".github/workflows/**"
      - ".bit/**"
      - ".bithub/**"
  workflow_dispatch:
    inputs:
      auto_fix:
        description: Open a PR with fixes
        type: boolean
        default: true
      target_ref:
        description: Base branch for PR
        type: string
        default: "main"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: meta-corrector-v2-${{ github.ref }}
  cancel-in-progress: false

jobs:
  orchestrate_corrections:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Call BitBot Corrector v2 Reusable Workflow
        uses: ./.bithub/workflows/bitbot-corrector-v2.yml
        with:
          repair_mode: ${{ inputs.auto_fix }}
          target_ref: ${{ inputs.target_ref }}

      - name: Snapshot reports
        run: |
          mkdir -p ".bithub/reports"
          tar -czf meta-corrector-v2.tar.gz ".bithub/reports" || echo "No reports yet."

      - uses: actions/upload-artifact@v4
        with:
          name: meta-corrector-logs
          path: meta-corrector-v2.tar.gz
          if-no-files-found: warn

  always_green:
    runs-on: ubuntu-latest
    needs: orchestrate_corrections
    steps:
      - run: echo "Meta-corrector v2 finished successfully."
