jobs:
  preflight-fix:
    runs-on: ubuntu-latest
    env:
      BIT_HUB_AUTOFIX: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.autorepair || (inputs.autorepair || 'false') }}
      ALLOWED_BOT_AUTHORS: "github-actions[bot],BitBot"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Guard & Gracefully Repair
        id: guard
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $autoFix = "$env:BIT_HUB_AUTOFIX" -eq 'true'
          $allowedAuthors = ($env:ALLOWED_BOT_AUTHORS -split ',') | ForEach-Object { $_.Trim() }
          $actor = "${{ github.actor }}"
          $branchRef = "${{ github.ref }}"
          $onMain = $branchRef -eq 'refs/heads/main'
          $violations = [System.Collections.Generic.List[string]]::new()
          $ledger = ".bithub/ledger/preflight.log"
          New-Item -ItemType Directory -Force -Path (Split-Path $ledger) | Out-Null

          function Add-Violation([string]$msg) { 
            Write-Host "❌ $msg"
            $violations.Add($msg) | Out-Null
          }
          function Log-Fix([string]$msg) {
            $ts = (Get-Date).ToString("o")
            Add-Content -Path $ledger -Value (@{ts=$ts;event="FIX";detail=$msg} | ConvertTo-Json -Compress)
            Write-Host "🛠 $msg"
          }

          Write-Host "🔍 Validating .bit architecture modal..."
          if (-not (Test-Path ".bit")) { Add-Violation ".bit directory is missing." }

          # 1) Enforce .bit extensions inside .bit, .bitrunners, .gitrunners
          $targets = @(".bit", ".bitrunners", ".gitrunners") | Where-Object { Test-Path $_ }
          foreach ($root in $targets) {
            $bad = Get-ChildItem -Path $root -Recurse -File | Where-Object {
              $_.Extension -ne ".bit" -and $_.Name -ne ".gitkeep"
            }
            if ($bad.Count -gt 0) {
              if ($autoFix) {
                foreach ($file in $bad) {
                  $new = [IO.Path]::ChangeExtension($file.FullName, ".bit")
                  git mv -- "$($file.FullName)" "$new"
                  Log-Fix "Renamed ${root}: '$($file.Name)' → '$([IO.Path]::GetFileName($new))'"
                }
              } else {
                $bad | ForEach-Object { Add-Violation "Non-.bit file in ${root}: $($_.FullName)" }
              }
            }
          }

          # 2) Enforce ALN manifests reside under .bit
          $alnOutside = Get-ChildItem -Recurse -File -Include *.aln | Where-Object {
            -not $_.FullName.StartsWith((Resolve-Path ".bit").Path + [IO.Path]::DirectorySeparatorChar)
          }
          if ($alnOutside.Count -gt 0) {
            if ($autoFix) {
              foreach ($f in $alnOutside) {
                $dest = Join-Path ".bit" $f.Name
                New-Item -ItemType Directory -Force -Path ".bit" | Out-Null
                git mv -- "$($f.FullName)" "$dest"
                Log-Fix "Moved ALN manifest into .bit: '$($f.FullName)' → '$dest'"
              }
            } else {
              $alnOutside | ForEach-Object { Add-Violation ".aln must live under .bit: $($_.FullName)" }
            }
          }

          # 3) Minimal schema presence check
          if (Test-Path ".bit") {
            if (-not (Test-Path ".bit/schema/bit-architecture.json")) {
              if ($autoFix) {
                New-Item -ItemType Directory -Force -Path ".bit/schema" | Out-Null
                Set-Content -Path ".bit/schema/bit-architecture.json" -Value '{ "$schema":"https://json-schema.org/draft/2020-12/schema", "title":"bit-architecture","type":"object" }' -Encoding UTF8
                git add .bit/schema/bit-architecture.json
                Log-Fix "Created missing schema: .bit/schema/bit-architecture.json"
              } else {
                Add-Violation "Missing .bit/schema/bit-architecture.json (schema contract)."
              }
            }
          }

          # 4) Runner governance presence
          foreach ($dir in @(".bitrunners",".gitrunners")) {
            if (-not (Test-Path $dir)) {
              if ($autoFix) {
                New-Item -ItemType Directory -Force -Path $dir | Out-Null
                New-Item -ItemType File -Force -Path (Join-Path $dir ".gitkeep") | Out-Null
                git add $dir
                Log-Fix "Created missing runner policy directory: ${dir}"
              } else {
                Add-Violation "Missing ${dir} runner policy directory."
              }
            }
          }

          # 5) Unauthorized .bit changes on main
          $bitChanges = (git diff --name-only origin/main...HEAD | Select-String '^\.bit/').ToString()
          if ($onMain -and $bitChanges) {
            $allowed = $false
            foreach ($a in $allowedAuthors) {
              if ($actor -match [regex]::Escape($a)) { $allowed = $true; break }
            }
            if (-not $allowed) {
              Add-Violation "Unauthorized modification to .bit on main by '$actor'. Allowed: $($allowedAuthors -join ', ')"
            }
          }

          # Exit or commit fixes
          if ($violations.Count -gt 0 -and -not $autoFix) {
            Write-Error "🔒 Guard failed with $($violations.Count) violation(s). Enable autorepair to normalize."
            exit 1
          }
          if ($autoFix) {
            $hasChanges = -not (git diff --quiet) -or -not (git diff --cached --quiet)
            if ($hasChanges) {
              git config --global user.name "github-actions[bot]"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git commit -m "ci(preflight): normalize names/paths for Bit.Hub compliance [skip ci]" || true
              if ($onMain) {
                git fetch origin main
                git pull --rebase origin main
                git push origin HEAD:main
              }
            } else {
              Write-Host "✅ No changes required after normalization."
            }
          }
