name: Comet Docker Image CI + ALN Governance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WINDOWS13_SAFE_MODE: true
  ADVANCED_MATRICULATION: "enabled"
  ALN_EXEC_POLICY: "content-execution"
  HUMAN_EQUALITY_PROTECTION: "constitutional"
  STRICT_AUDIT_LOGGING: 1

jobs:
  swarmnet-governance:
    name: SwarmNet Governance Enforcer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Audit ALN Compliance
        run: |
          echo "::group::ALN Sanity Validation"
          python scripts/aln_audit.py --strict --output audit.log
          echo "::endgroup::"
      - name: Enforce Hardware Safe-Mode (Arithmetic Check)
        run: |
          if (( $(nproc) < 2 )); then echo "Insufficient CPU cores for safe operation." && exit 1; fi
          MEM_GB=$(awk '/MemTotal/ {print int($2/1024/1024)}' /proc/meminfo)
          if (( $MEM_GB < 8 )); then echo "Minimum RAM threshold not met: ${MEM_GB}GB"; exit 2; fi
      - name: Validate Immutable Chronicle Logging
        run: |
          echo "log_event('ALN_INIT', user='$GITHUB_ACTOR', status='initiated')" | tee -a chronicle_events.log

  docker:
    needs: swarmnet-governance
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image (Safe, ALN Tagged)
        run: |
          SAFE_RUN=$([ "$WINDOWS13_SAFE_MODE" = "true" ] && echo "--security-opt=no-new-privileges")
          docker build . --file Dockerfile --tag comet:${{ github.sha }} $SAFE_RUN

      - name: Adaptive ALN Calculation Step
        run: |
          echo "Calculating stabilization vector..."
          # Advanced calculation: matrix product for context integrity, n=10
          python scripts/matrix_integrity_check.py --size 10 --audit-mode force

      - name: Post-Build Chronicle Anchor
        run: |
          echo "anchor_data('build-${GITHUB_SHA}', content_hash=sha256sum Dockerfile)" >> chronicle_events.log

      - name: Summarize & Artifact Results
        run: |
          tar czf governance_artifacts.tar.gz audit.log chronicle_events.log
        if: always()
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.1.0
        with:
          name: governance_artifacts
          path: governance_artifacts.tar.gz

  stale-monitor:
    name: Issue/PR Stale Governance
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues & PRs
        uses: actions/stale@v10.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Please update or confirm activity for continued SwarmNet compatibility."
          close-issue-message: "Closed for governance and ALN compliance—may be re-opened with new evidence/interest."
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: "critical,compliance,governance"
          exempt-pr-labels: "critical,compliance,governance"

# Adaptive, advanced, and ALN-safe by default. All code embodies real-world safe-separation of constitutional/human-equality, privacy, and rational, mathematical integrity.
